#ifndef STATEMACHINE_H
#define STATEMACHINE_H

/**
 * @brief      Enumerator defines different states in the HAB mission
 */
enum MissionState 
{
	STAGING,
	TAKEOFF,
	ASCENDING,
	DESCENDING,
	LANDING,
	RECOVERY,
	RECOVERED
};

/**
 * Define the behaviour of the system under different states
 */
#define STAGING_CHECK_TELEMETRY_INTERVAL 1000
#define STAGING_REPORT_TELEMETRY_INTERVAL 5000
#define STAGING_LOG_TELEMETRY_INTERVAL 5000
#define STAGING_REPORT_POSITION_INTERVAL 30000
#define STAGING_BEEPER_ENABLED false
#define STAGING_LED_ENABLED true

#define TAKEOFF_CHECK_TELEMETRY_INTERVAL 1000
#define TAKEOFF_REPORT_TELEMETRY_INTERVAL 15000
#define TAKEOFF_LOG_TELEMETRY_INTERVAL 5000
#define TAKEOFF_REPORT_POSITION_INTERVAL 15000
#define TAKEOFF_BEEPER_ENABLED true
#define TAKEOFF_LED_ENABLED true

#define ASCENDING_CHECK_TELEMETRY_INTERVAL 1000
#define ASCENDING_REPORT_TELEMETRY_INTERVAL 60000
#define ASCENDING_LOG_TELEMETRY_INTERVAL 5000
#define ASCENDING_REPORT_POSITION_INTERVAL 30000
#define ASCENDING_BEEPER_ENABLED false
#define ASCENDING_LED_ENABLED false

#define DESCENDING_CHECK_TELEMETRY_INTERVAL 1000
#define DESCENDING_REPORT_TELEMETRY_INTERVAL 60000
#define DESCENDING_LOG_TELEMETRY_INTERVAL 5000
#define DESCENDING_REPORT_POSITION_INTERVAL 30000
#define DESCENDING_BEEPER_ENABLED false
#define DESCENDING_LED_ENABLED false

#define LANDING_CHECK_TELEMETRY_INTERVAL 1000
#define LANDING_REPORT_TELEMETRY_INTERVAL 60000
#define LANDING_LOG_TELEMETRY_INTERVAL 5000
#define LANDING_REPORT_POSITION_INTERVAL 5000
#define LANDING_BEEPER_ENABLED true
#define LANDING_LED_ENABLED true

#define RECOVERY_CHECK_TELEMETRY_INTERVAL 1000
#define RECOVERY_REPORT_TELEMETRY_INTERVAL 300000
#define RECOVERY_LOG_TELEMETRY_INTERVAL 5000
#define RECOVERY_REPORT_POSITION_INTERVAL 300000
#define RECOVERY_BEEPER_ENABLED true
#define RECOVERY_LED_ENABLED true

#define RECOVERED_CHECK_TELEMETRY_INTERVAL 1000
#define RECOVERED_REPORT_TELEMETRY_INTERVAL 900000
#define RECOVERED_LOG_TELEMETRY_INTERVAL 5000
#define RECOVERED_REPORT_POSITION_INTERVAL 900000
#define RECOVERED_BEEPER_ENABLED false
#define RECOVERED_LED_ENABLED false

#endif
