#ifndef MESSAGEDEFINITIONS_H
#define MESSAGEDEFINITIONS_H

enum MESSAGE_TYPE
{
	/*---Report Messages---*/
	MESSAGE_TYPE_REPORT_TELEMETRY,
	MESSAGE_TYPE_REPORT_POSITION,

	/*---Command Messages---*/
	MESSAGE_TYPE_COMMAND_TAKEOFF,
	MESSAGE_TYPE_COMMAND_ABORT_TAKEOFF,
	MESSAGE_TYPE_COMMAND_SET_STATE,

	/*---Protocol Messages--*/
	MESSAGE_TYPE_PROTO_ACK,
	MESSAGE_TYPE_PROTO_NACK
};

#endif